---
- hosts: bastion
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ bastion_privatekey }}"
    ansible_become: true
  tasks:
  - name: Configure bastion
    import_role:
      name: idm
    
  - name: Prepare for deploying ROSA
    import_role:
      name: rosa